# spring.application.name=backend
# spring.profiles.active=local
# # spring.datasource.url=jdbc:postgresql://db.ditrpxtnudjmjfobiaul.supabase.co:5432/postgres?connectTimeout=5
# spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:6543/postgres?connectTimeout=5
# spring.datasource.username=postgres
# spring.jpa.hibernate.ddl-auto=none


# FIXED I HOPE
spring.application.name=backend
spring.profiles.active=local
# 6543
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?connectTimeout=5
spring.datasource.username=postgres.ditrpxtnudjmjfobiaul
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.minimumIdle=0

# Supabase OAuth
supabase.url=YOUR_SUPABASE_URL
supabase.anon-key=YOUR_SUPABASE_ANON_KEY


# Gemini
gemini.api.key=${GEMINI_API_KEY:}
gemini.model=${GEMINI_MODEL:gemini-2.5-flash}
