spring.application.name=backend
spring.profiles.active=local
spring.datasource.url=jdbc:postgresql://db.ditrpxtnudjmjfobiaul.supabase.co:5432/postgres?connectTimeout=5
spring.datasource.username=postgres
spring.jpa.hibernate.ddl-auto=none
