spring.application.name=backend
spring.datasource.url=jdbc:postgresql://db.ditrpxtnudjmjfobiaul.supabase.co:5432/postgres?connectTimeout=5
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
